Fix tic tac toe bug
CSI-280/MusicGames pull request #68
Opened 2020-04-21 02:18 UTC by jbuzzell

closes #54

also keeps timeout & disallows clicks after game is won

2020-04-21 02:18 UTC, jbuzzell commented
@CSI-280/web-people big one folks!

2020-04-23 01:55 UTC, NathanDiMauro requested changes
I think the game should still be replayable after the user has won. Now the game just freezes after they win.

2020-04-27 17:59 UTC, jbuzzell commented
@NathanDiMauro change implemented, i just forgot to un-freeze the board after the game reset

2020-04-27 18:00 UTC, NathanDiMauro approved these changes

2020-04-27 18:01 UTC, merged